camera_topics:
  cam_head: /astribot_whole_body/camera/head_rgbd/image_raw
  cam_left_wrist: /astribot_whole_body/camera/left_wrist_rgbd/image_raw
  cam_right_wrist: /astribot_whole_body/camera/right_wrist_rgbd/image_raw

state_topics:
  torso: /astribot_torso/joint_space_states
  left_arm: /astribot_arm_left/joint_space_states
  right_arm: /astribot_arm_right/joint_space_states
  left_gripper: /astribot_gripper_left/joint_space_states
  right_gripper: /astribot_gripper_right/joint_space_states
  head: /astribot_head/joint_space_states

required_state_parts: [torso, left_arm, right_arm, left_gripper, right_gripper, head]

command_topics:
  torso: /astribot_torso/joint_space_command
  left_arm: /astribot_arm_left/joint_space_command
  right_arm: /astribot_arm_right/joint_space_command
  left_gripper: /astribot_gripper_left/joint_space_command
  right_gripper: /astribot_gripper_right/joint_space_command
  head: /astribot_head/joint_space_command

command_stream:
  publish_hz: 250.0
  arm_velocity_limit: 8.0
